import { GoogleGenAI } from "@google/genai";
import { AdTheme } from "../types";

// Note: For video generation, we ensure the instance uses the latest key if reset.
let ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Re-initialize the AI client (useful if key changes or for safety before expensive calls)
 */
export const refreshAIClient = () => {
  ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
};

/**
 * Uses Gemini 2.5 Flash Image to edit/generate a scene based on the product image.
 */
export const generateAdScene = async (
  base64Image: string,
  narrative: string,
  theme: AdTheme,
  mode: 'generate' | 'edit' = 'generate'
): Promise<string> => {
  try {
    refreshAIClient();
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
    let fullPrompt = '';

    if (mode === 'edit') {
       fullPrompt = `
        You are an expert advertising photographer and image editor.
        Task: Edit the provided image based strictly on the user's instruction.
        
        IMPORTANT: The user may provide instructions in Portuguese. Follow them precisely.
        User Instruction: "${narrative}"
        
        Requirements:
        1. Maintain the high quality and photorealism of the original image.
        2. Apply the requested change (e.g., filter, object removal, addition, lighting change) naturally.
        3. Do not add text to the image itself.
        4. If the user asks to remove something, fill the space naturally (inpainting).
        5. If the user asks to add a filter (e.g. retro, black and white), apply it globally.
      `;
    } else {
      const themeInstruction = getThemeInstruction(theme);
      
      fullPrompt = `
        You are an expert advertising photographer and editor.
        Task: Create a stunning product advertisement using the provided product image.
        
        IMPORTANT: The user may provide instructions in Portuguese. Interpret them for the visual context.
        User Narrative/Request: "${narrative}"
        Visual Style: ${themeInstruction}
        
        Instructions:
        1. Keep the main product from the input image clearly visible and central.
        2. CONTEXT AWARENESS: If the narrative implies a person or usage (e.g. "woman holding it", "man wearing it"), generate a realistic human model/avatar interacting with the product naturally.
        3. ENVIRONMENT: Completely transform the background and lighting to match the 'Visual Style' and 'User Narrative'.
        4. OUTPUT QUALITY: Ensure high quality, photorealistic output suitable for social media ads.
        5. Do not add text to the image itself.
        6. COMPOSITION: Ensure the product is the focal point.
      `;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', 
              data: cleanBase64,
            },
          },
          {
            text: fullPrompt,
          },
        ],
      },
    });

    let generatedImageBase64 = '';
    
    if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                generatedImageBase64 = part.inlineData.data;
                break;
            }
        }
    }

    if (!generatedImageBase64) {
      throw new Error("No image generated by Gemini.");
    }

    return `data:image/png;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

/**
 * Uses Veo (veo-3.1-fast-generate-preview) to generate a video.
 */
export const generateAdVideo = async (
  base64Image: string,
  narrative: string,
  theme: AdTheme,
  aspectRatio: '16:9' | '9:16'
): Promise<string> => {
  try {
    refreshAIClient();
    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
    const themeInstruction = getThemeInstruction(theme);

    // Prompt optimized for video motion
    const prompt = `
      Cinematic product video, commercial advertisement style. 
      Theme: ${themeInstruction}.
      Action/Narrative: ${narrative}.
      High quality, 4k, fluid motion, professional lighting.
    `;

    console.log("Starting video generation...");
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt,
      image: {
        imageBytes: cleanBase64,
        mimeType: 'image/png', 
      },
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: aspectRatio
      }
    });

    console.log("Video operation started, polling...", operation);

    // Poll for completion
    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 5000)); // Poll every 5 seconds
      operation = await ai.operations.getVideosOperation({operation: operation});
      console.log("Polling status:", operation.metadata);
    }

    const videoUri = operation.response?.generatedVideos?.[0]?.video?.uri;
    
    if (!videoUri) {
      throw new Error("Video generation completed but no URI returned.");
    }

    // Fetch the actual video bytes using the API key
    const response = await fetch(`${videoUri}&key=${process.env.API_KEY}`);
    if (!response.ok) {
        throw new Error(`Failed to download video: ${response.statusText}`);
    }
    
    const blob = await response.blob();
    return URL.createObjectURL(blob);

  } catch (error) {
    console.error("Veo API Error:", error);
    throw error;
  }
}

const getThemeInstruction = (theme: AdTheme): string => {
  switch (theme) {
    case AdTheme.MINIMAL:
      return "Clean, soft lighting, solid or subtle gradient background, modern shadows, ample whitespace, minimalistic studio.";
    case AdTheme.LUXURY:
      return "Dark moody lighting, gold or marble accents, expensive textures, silk, high contrast, elegant atmosphere.";
    case AdTheme.SUMMER:
      return "Bright sunlight, beach or pool background, blue skies, palm trees, warm saturation, vacation vibes.";
    case AdTheme.FASHION:
      return "Urban street photography style, dynamic angles, concrete textures, trendy outfit context, high fashion editorial.";
    case AdTheme.RETRO:
      return "Vintage film grain, 90s pastel colors, polaroid aesthetic, flash photography look, nostalgic.";
    case AdTheme.FUTURISTIC:
      return "Neon lights, dark tech background, cyber aesthetics, glowing elements, sci-fi atmosphere.";
    default:
      return "Professional studio lighting.";
  }
};