import { GoogleGenAI } from "@google/genai";
import { AdTheme } from "../types";

/**
 * Uses Gemini 2.5 Flash Image to edit/generate a scene based on the product image.
 * 
 * Note: We initialize the client inside the function to avoid 'process is not defined' 
 * errors during initial page load in some client-side environments (like Netlify static deploy).
 */
export const generateAdScene = async (
  base64Image: string,
  narrative: string,
  theme: AdTheme,
  mode: 'generate' | 'edit' = 'generate',
  aspectRatio: string = '1:1'
): Promise<string> => {
  try {
    // SAFE INITIALIZATION:
    // In many build tools (Vite, Webpack), process.env.API_KEY is replaced by string literal at build time.
    // However, checking 'process.env' directly without checking 'typeof process' can crash browsers.
    // The standard way for these AI prompts is simply accessing process.env.API_KEY, assuming the bundler handles it.
    
    // @ts-ignore - process might not be defined in browser types, but bundler replaces it.
    const apiKey = process.env.API_KEY; 
    
    if (!apiKey) {
      throw new Error("API_KEY não encontrada. Verifique as variáveis de ambiente.");
    }

    const ai = new GoogleGenAI({ apiKey: apiKey });

    const cleanBase64 = base64Image.replace(/^data:image\/(png|jpeg|jpg|webp);base64,/, '');
    let fullPrompt = '';

    if (mode === 'edit') {
       fullPrompt = `
        Generate an edited image.
        You are an expert advertising photographer and image editor.
        Task: Edit the provided image based strictly on the user's instruction.
        
        IMPORTANT: The user may provide instructions in Portuguese. Follow them precisely.
        User Instruction: "${narrative}"
        
        Requirements:
        1. Maintain the high quality and photorealism of the original image.
        2. Apply the requested change (e.g., filter, object removal, addition, lighting change) naturally.
        3. Do not add text to the image itself.
        4. If the user asks to remove something, fill the space naturally (inpainting).
        5. If the user asks to add a filter (e.g. retro, black and white), apply it globally.
      `;
    } else {
      const themeInstruction = getThemeInstruction(theme);
      
      fullPrompt = `
        Generate an image.
        You are an expert advertising photographer and editor.
        Task: Create a stunning product advertisement using the provided product image.
        
        IMPORTANT: The user may provide instructions in Portuguese. Interpret them for the visual context.
        User Narrative/Request: "${narrative}"
        Visual Style: ${themeInstruction}
        
        Instructions:
        1. Keep the main product from the input image clearly visible and central.
        2. CONTEXT AWARENESS: If the narrative implies a person or usage (e.g. "woman holding it", "man wearing it"), generate a realistic human model/avatar interacting with the product naturally.
        3. ENVIRONMENT: Completely transform the background and lighting to match the 'Visual Style' and 'User Narrative'.
        4. OUTPUT QUALITY: Ensure high quality, photorealistic output suitable for social media ads.
        5. Do not add text to the image itself.
        6. COMPOSITION: Ensure the product is the focal point.
      `;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', 
              data: cleanBase64,
            },
          },
          {
            text: fullPrompt,
          },
        ],
      },
      config: {
        imageConfig: {
            aspectRatio: aspectRatio as any, // 1:1, 3:4, 4:3, 9:16, 16:9
        }
      }
    });

    let generatedImageBase64 = '';
    let textOutput = '';
    
    if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
            if (part.inlineData) {
                generatedImageBase64 = part.inlineData.data;
            } else if (part.text) {
                textOutput += part.text;
            }
        }
    }

    if (!generatedImageBase64) {
      if (textOutput) {
         throw new Error(`A IA não gerou a imagem. Resposta: "${textOutput}"`);
      }
      throw new Error("No image generated by Gemini (and no text explanation).");
    }

    return `data:image/png;base64,${generatedImageBase64}`;

  } catch (error) {
    console.error("Gemini API Error:", error);
    throw error;
  }
};

const getThemeInstruction = (theme: AdTheme): string => {
  switch (theme) {
    case AdTheme.MINIMAL:
      return "Clean, soft lighting, solid or subtle gradient background, modern shadows, ample whitespace, minimalistic studio.";
    case AdTheme.LUXURY:
      return "Dark moody lighting, gold or marble accents, expensive textures, silk, high contrast, elegant atmosphere.";
    case AdTheme.SUMMER:
      return "Bright sunlight, beach or pool background, blue skies, palm trees, warm saturation, vacation vibes.";
    case AdTheme.FASHION:
      return "Urban street photography style, dynamic angles, concrete textures, trendy outfit context, high fashion editorial.";
    case AdTheme.RETRO:
      return "Vintage film grain, 90s pastel colors, polaroid aesthetic, flash photography look, nostalgic.";
    case AdTheme.FUTURISTIC:
      return "Neon lights, dark tech background, cyber aesthetics, glowing elements, sci-fi atmosphere.";
    default:
      return "Professional studio lighting.";
  }
};